version: '3'
services:
  app:
    build: .
    ports:
      - "23002:23002"
    volumes:
      - ./data:/app/data
    environment:
      - NODE_ENV=production
      - PORT=23002
      - BASE_URL=fshare.tubik-corp.ru